<a href="https://colab.research.google.com/github/mkh-ai/numpy-library/blob/main/arifmetik_amallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 24.06.2022
import numpy as np

In [4]:
arr1 = np.arange(6).reshape(3,2)
arr2 = np.arange(6,12).reshape(3,2)


** arr1 ning elementlarini arr2 ning mos elementlariga kopaytirish**

In [6]:
arr1*arr2

array([[ 0,  7],
       [16, 27],
       [40, 55]])

**bo'lish**

In [7]:
arr2/arr1

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[inf, 7. ],
       [4. , 3. ],
       [2.5, 2.2]])

****Ayirish

In [8]:
arr2-arr1

array([[6, 6],
       [6, 6],
       [6, 6]])

**Kvadratga oshirish**

In [9]:
arr1**2

array([[ 0,  1],
       [ 4,  9],
       [16, 25]])

**Ildizdan chiqarish**

In [10]:
arr2**0.5

array([[2.44948974, 2.64575131],
       [2.82842712, 3.        ],
       [3.16227766, 3.31662479]])