<a href="https://colab.research.google.com/github/mkh-ai/numpy-library/blob/main/Array_oqlarini_almashtirish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

**reshape metodi**

In [8]:
A = np.arange(10).reshape(5,2)
A

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

**Transpoese metodi**

In [9]:
A.T  # A massiivni transpose korinishi

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

**Swapaxes metodi**

In [11]:
A.swapaxes(1,0)   # A massiivni transpose korinishi

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

**Transposeni ishlatilishiga bir missol**

In [12]:
A

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [14]:
np.dot(A,A.T)  # AA^T dan hosil bolgan masssiv

array([[  1,   3,   5,   7,   9],
       [  3,  13,  23,  33,  43],
       [  5,  23,  41,  59,  77],
       [  7,  33,  59,  85, 111],
       [  9,  43,  77, 111, 145]])