<a href="https://colab.research.google.com/github/mkh-ai/numpy-library/blob/main/Copy_of_Boolean_indexing_md.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
names = np.array(['Asad', 'Ali', 'Vali', 'Otabek', 'Ayub'])
names

array(['Asad', 'Ali', 'Vali', 'Otabek', 'Ayub'], dtype='<U6')

In [ ]:
names == 'Asad'  # Asadga tegisshli barcha elementlarni chop qilish

array([ True, False, False, False, False])

In [ ]:
data = np.random.randn(5,5)
data

array([[ 0.07017478, -2.32594003, -1.23338076,  0.58049092,  0.48475095],
       [ 0.28994625, -0.09235025, -1.1603932 ,  1.32272567,  0.41435842],
       [-0.62553751, -2.3343182 ,  0.00822624,  1.7129823 , -0.71861862],
       [-0.02112631,  1.40485348, -0.01224337,  0.58798328,  1.04907213],
       [ 0.09065647,  1.75086347,  0.8113565 ,  0.30814313,  1.45927979]])

In [ ]:
data[names == 'Vali']

array([[ 0.98385711, -1.47998601, -2.17816794,  1.9882789 ,  0.79358146,
        -0.37040359]])

In [ ]:
data[names == 'Ali',2:] # Aliga tegishli oxirgi uchta elementni kesib olish

array([[-0.02016945,  1.56570464, -0.57067705]])

In [ ]:
#data[names != 'Vali'] # Validan boshqa barcha elementlarni kesib olish
data[~(names == 'Vali')]

array([[ 0.9650415 , -0.31649118,  0.9063698 ,  0.07077208,  0.8346766 ],
       [ 0.11919231, -1.14011356, -0.02016945,  1.56570464, -0.57067705],
       [ 0.09964738, -0.10651977,  0.08406252, -0.07810588,  0.38119861],
       [-0.92226115, -1.21632039,  0.83849599,  2.50261194,  0.25337777]])

In [ ]:
print(names)
print(data)

['Asad' 'Ali' 'Vali' 'Otabek' 'Ayub']
[[ 0.07017478 -2.32594003 -1.23338076  0.58049092  0.48475095]
 [ 0.28994625 -0.09235025 -1.1603932   1.32272567  0.41435842]
 [-0.62553751 -2.3343182   0.00822624  1.7129823  -0.71861862]
 [-0.02112631  1.40485348 -0.01224337  0.58798328  1.04907213]
 [ 0.09065647  1.75086347  0.8113565   0.30814313  1.45927979]]


In [ ]:
mask = (names == 'Ayub') | (names == 'Ali') # Ayub va Aliga tegishli malumotlarni kesib olish
mask

array([False,  True, False, False,  True])

**Ayub va Aliga tegishli malumotlarni kesib olish**

In [ ]:
data[mask] # Ayub va Aliga tegishli malumotlarni kesib olish

array([[ 0.28994625, -0.09235025, -1.1603932 ,  1.32272567,  0.41435842],
       [ 0.09065647,  1.75086347,  0.8113565 ,  0.30814313,  1.45927979]])

In [ ]:
data[data<0] = 0 # 0 dan kichik malumotlarni 0 ga tenglash
data

array([[0.07017478, 0.        , 0.        , 0.58049092, 0.48475095],
       [0.28994625, 0.        , 0.        , 1.32272567, 0.41435842],
       [0.        , 0.        , 0.00822624, 1.7129823 , 0.        ],
       [0.        , 1.40485348, 0.        , 0.58798328, 1.04907213],
       [0.09065647, 1.75086347, 0.8113565 , 0.30814313, 1.45927979]])