<a href="https://colab.research.google.com/github/mkh-ai/numpy-library/blob/main/data_types_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np # numpy kutubxonasini chaqirib olamiz

In [2]:
arr = np.array([4,6,7,8], dtype = np.int64) # int64  malumotlar turiga ega massiv
arr

array([4, 6, 7, 8])

In [3]:
arr1 = np.array([6.7,8.8,9.99,3,4], dtype=np.float32) # float32 malumotlar turiga ega massiv
arr1

array([6.7 , 8.8 , 9.99, 3.  , 4.  ], dtype=float32)

**dtype metodi**

In [4]:
arr.dtype

dtype('int64')

In [5]:
arr1.dtype

dtype('float32')

# Bir turdagi malumot turini boshqasiga ogirish


astype metodi

In [5]:
arr2 = np.array([1,2,3,4,6]) # int64 turidagi massiv
arr2.dtype

dtype('int64')

In [6]:
float_arr2 = arr2.astype(np.float32)
float_arr2.dtype

dtype('float32')

In [8]:
arr3 = np.array([3.5, 4.6, 2.7]) # float64 turidagi massiv
arr3.dtype

dtype('float64')

In [9]:
int_arr3 = arr3.astype(np.int16)
int_arr3

array([3, 4, 2], dtype=int16)