<a href="https://colab.research.google.com/github/mkh-ai/numpy-library/blob/main/Fayllar_bilan_ishlash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Fayllar bilan ishlash
# 30.06.2022

import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.save('data', arr) 
        

load() malumotlarni chop qilish

In [5]:
arr2 = np.load('data.npy')
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr1 = np.arange(20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

**savez metodi**

In [9]:
# Array ichiga bir nechta malumotlarni saqlash

np.savez('arrays', a=arr , b = arr1)


In [10]:
arrays = np.load('arrays.npz')
arrays['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# kalit soz orqali malumotlarni chaqirish
arrays['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

**savez_compressed metodi**

In [ ]:
# malumotlarni hajmini siqib beradi

np.savez_compressed('arrauy_comp.npz', a = arr, b = arr1)
