<a href="https://colab.research.google.com/github/mkh-ai/numpy-library/blob/main/indexing_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Bismillah

In [2]:
import numpy as np

In [3]:
arr = np.arange(1,20,3)
arr

array([ 1,  4,  7, 10, 13, 16, 19])

In [6]:
arr[2:5]

array([ 7, 10, 13])

# 2d olchamli masivlarni indekslash va kesib olish
\

In [7]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d                 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
arr2d[2,2]

9

In [10]:
arr2d[1,2:]

array([6])

# 3d olchamli massivlarni indeksslash va kesish

In [11]:
arr3d = np.array([[[1,2,3],
                  [4,5,6],
                  [7,8,9]],
                 
                 [[10,11,12],
                  [13,14,15],
                  [16,17,18]],
                 
                 [[19,20,21],
                  [22,23,24],
                  [25,26,27]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [19]:
arr3d[1][1,:2]


array([13, 14])

In [21]:
arr3d[2][0,:2]

array([19, 20])