<a href="https://colab.research.google.com/github/mkh-ai/numpy-library/blob/main/Malumotlar_tahlili.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 24.06.2022
# Malumotlar tahlili

import numpy as np

In [2]:
arr = np.random.randn(4,5)
arr

array([[ 0.41439959,  1.15678146, -1.51670054, -1.20954032,  1.23359503],
       [-0.4904666 ,  0.26789774, -0.1896194 , -1.01038729,  0.55012298],
       [ 1.64781573, -1.14137024,  0.46579142, -0.69968172, -0.42368045],
       [ 0.30227709,  0.09440451,  0.43258219,  0.10541161,  0.08770142]])

**SUM() metodi**

In [3]:
arr.sum() #arrayning barcha elementlarini yigindisini hisoblab beradi
# np.sum(arr)

0.07733420572008014

In [4]:
arr.sum(axis=1) # qator yigindisi

array([ 0.07853522, -0.87245257, -0.15112527,  1.02237682])

In [5]:
arr.sum(axis=0) # ustunlar yigindisi

array([ 1.87402582,  0.37771346, -0.80794633, -2.81419772,  1.44773898])

**mean() metodi**

In [6]:
data = np.arange(8)
data

array([0, 1, 2, 3, 4, 5, 6, 7])

In [9]:
mean = np.sum(data)/len(data) # arrayning orta arifmetigini topish
mean

3.5

In [11]:
#data.mean()
np.mean(data)

3.5

In [12]:
np.mean(arr, axis=0) # arrayning ustunlar yigindisini topish

array([ 0.46850645,  0.09442837, -0.20198658, -0.70354943,  0.36193474])

**CUMSUM() metodi**

In [13]:
data

array([0, 1, 2, 3, 4, 5, 6, 7])

In [14]:
data.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])