<a href="https://colab.research.google.com/github/mkh-ai/numpy-library/blob/main/Mantiqiy_shart_operatorlari.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#24.06.2022
import numpy as np

# Shart operatori sifatida where dan foydalanish

In [9]:
xarr = np.arange(1.1,1.6,0.1)
yarr = np.arange(2.1,2.6,0.1)


In [12]:
cond = np.array([True, False, True, False, True])

In [13]:
result = np.where(cond,xarr,yarr)
result

array([1.1, 2.2, 1.3, 2.4, 1.5])

In [15]:
arr = np.random.randn(5,5)
arr

array([[-1.0653714 ,  1.76063089,  0.13012897, -0.76835113,  0.07440891],
       [ 0.33899686,  0.59255037,  0.42997789, -0.99607905, -0.68615986],
       [-0.17257732,  0.98736937, -0.14058188,  1.46821637, -0.31837791],
       [ 0.07398138,  0.62010885,  0.26542044, -0.98357043,  1.77845334],
       [ 1.18358738, -0.81582796,  1.33861247, -0.18269021, -2.17187917]])

In [17]:
results = np.where(arr <0 ,-2 , 2 , )  # massivning musbat elementlarini 2 ga, manfiy elementlarini -2 ga almashtirish
results

array([[-2,  2,  2, -2,  2],
       [ 2,  2,  2, -2, -2],
       [-2,  2, -2,  2, -2],
       [ 2,  2,  2, -2,  2],
       [ 2, -2,  2, -2, -2]])