<a href="https://colab.research.google.com/github/mkh-ai/numpy-library/blob/main/Tartiblash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# 27.06.2022
# Sorting
import numpy as np

#SORT funksiyasi 

In [2]:
arr =  np.random.randn(5)
arr

array([-0.04666387, -0.42424009,  0.23439164, -0.58660401, -0.50809649])

In [3]:
sorted_arr = np.sort(arr) # arrayni tartiblash
sorted_arr

array([-0.58660401, -0.50809649, -0.42424009, -0.04666387,  0.23439164])

In [5]:
arr.sort() # arrayni tartiblash 2-usuli
arr

array([-0.58660401, -0.50809649, -0.42424009, -0.04666387,  0.23439164])

**Teskari tartiblash**

In [6]:
rev_arr = -np.sort(-arr)
rev_arr

array([ 0.23439164, -0.04666387, -0.42424009, -0.50809649, -0.58660401])

In [7]:
# 2d massiv
arr2d = np.random.randn(2,4)
arr2d

array([[-1.23974209,  0.56331622, -0.14369105, -1.31346925],
       [ 1.81176366,  0.90659967, -0.54304064, -0.37408878]])

In [8]:
# axis = 0 -->> Qator
row_sort = np.sort(arr2d, axis = 0)
row_sort

array([[-1.23974209,  0.56331622, -0.54304064, -1.31346925],
       [ 1.81176366,  0.90659967, -0.14369105, -0.37408878]])

In [10]:
# axis = 1 -->> Ustun

column_sort = np.sort(arr2d , axis =1)
column_sort

array([[-1.31346925, -1.23974209, -0.14369105,  0.56331622],
       [-0.54304064, -0.37408878,  0.90659967,  1.81176366]])