<a href="https://colab.research.google.com/github/mkh-ai/numpy-library/blob/main/transposing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Bismillah

In [2]:
import numpy as np

# ReShape metodi

In [7]:
A = np.arange(6).reshape(2,3)
A

array([[0, 1, 2],
       [3, 4, 5]])

#Transpose

In [9]:
A.T # A massivning transpose korinishi

array([[0, 3],
       [1, 4],
       [2, 5]])

In [15]:
A

array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
A.swapaxes(1,0) # 2-usuli


array([[0, 3],
       [1, 4],
       [2, 5]])

# Tranposening ishlatilinishiga bir misol 

In [20]:
A

array([[0, 1, 2],
       [3, 4, 5]])

In [22]:
np.dot(A,A.T)

array([[ 5, 14],
       [14, 50]])