<a href="https://colab.research.google.com/github/mkh-ai/numpy-library/blob/main/Unversal_funksiyalar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 24.06.2022
mport numpy as np

# Unary funksiyalar(Bitta qiymat qabul qiluvchi funksiyalar)

In [2]:
arr = np.arange(0,24,4)
arr

array([ 0,  4,  8, 12, 16, 20])

**sqrt massivning har bir elementini kvadrat ildizini qaytaradi**

In [3]:
np.sqrt(arr)

array([0.        , 2.        , 2.82842712, 3.46410162, 4.        ,
       4.47213595])

**square massivning har bir elementini kvadratga oshiradi**

In [4]:
np.square(arr)

array([  0,  16,  64, 144, 256, 400])

**exp massivning har bir elemntini exponentini qaytaradi**

In [5]:
np.exp(arr)

array([1.00000000e+00, 5.45981500e+01, 2.98095799e+03, 1.62754791e+05,
       8.88611052e+06, 4.85165195e+08])

***modf funksiyasi haqiqiy sonlarni butun va qoldiq qismlarini ajratib beradi***

In [7]:
arr1 = np.random.randn(5)
arr1

array([-0.78084451,  0.51121577,  1.53913181,  1.17558922,  0.61685518])

In [9]:
qoldiq , butun= np.modf(arr1)
print(butun)
print(qoldiq)

[-0.  0.  1.  1.  0.]
[-0.78084451  0.51121577  0.53913181  0.17558922  0.61685518]


**sign funksiyasi qiymat manfiy bolsa -1, musbat bolsa 1 ni qaytaradi**

In [10]:
np.sign(arr1)

array([-1.,  1.,  1.,  1.,  1.])

# Binary functions (2 ta argument qabul qiluvchi funksiya)

In [17]:
arr2 = np.random.randn(5)
arr3 = np.random.randn(5)

In [18]:
arr2

array([ 1.43034213,  0.81585058,  0.87823242,  1.02684645, -0.67379003])

In [19]:
arr3

array([-0.16409017,  0.43390759, -0.1962809 , -0.84799767, -0.66298235])

**add metodi ikki massivning mos elementlarini qoshadi**

In [20]:
np.add(arr2,arr3)
# arr2 + arrr3

array([ 1.26625195,  1.24975817,  0.68195152,  0.17884878, -1.33677238])

**multiply ikkita massivning mos qiymatlarini kopaytiradi**

In [21]:
np.multiply(arr2,arr3)

array([-0.23470509,  0.35400376, -0.17238025, -0.87076339,  0.4467109 ])

**maximum : ikkita masssivni mos qiymatlarini taqqoslab kattasini oladi**

In [24]:
np.maximum(arr2,arr3)

array([ 1.43034213,  0.81585058,  0.87823242,  1.02684645, -0.66298235])